/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as mainNotificationsIndexRouteImport } from './routes/(main)/notifications/index'
import { Route as mainHistoryIndexRouteImport } from './routes/(main)/history/index'
import { Route as mainNotificationsNotificationIdRouteImport } from './routes/(main)/notifications/$notificationId'
import { Route as mainHistoryRedemptionIdRouteImport } from './routes/(main)/history/$redemptionId'
import { Route as mainVouchersVoucherIdIndexRouteImport } from './routes/(main)/vouchers/$voucherId/index'
import { Route as mainVouchersVoucherIdRedeemRouteImport } from './routes/(main)/vouchers/$voucherId/redeem'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainNotificationsIndexRoute = mainNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainHistoryIndexRoute = mainHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainNotificationsNotificationIdRoute =
  mainNotificationsNotificationIdRouteImport.update({
    id: '/notifications/$notificationId',
    path: '/notifications/$notificationId',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainHistoryRedemptionIdRoute = mainHistoryRedemptionIdRouteImport.update({
  id: '/history/$redemptionId',
  path: '/history/$redemptionId',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainVouchersVoucherIdIndexRoute =
  mainVouchersVoucherIdIndexRouteImport.update({
    id: '/vouchers/$voucherId/',
    path: '/vouchers/$voucherId/',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainVouchersVoucherIdRedeemRoute =
  mainVouchersVoucherIdRedeemRouteImport.update({
    id: '/vouchers/$voucherId/redeem',
    path: '/vouchers/$voucherId/redeem',
    getParentRoute: () => mainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof mainIndexRoute
  '/history/$redemptionId': typeof mainHistoryRedemptionIdRoute
  '/notifications/$notificationId': typeof mainNotificationsNotificationIdRoute
  '/history/': typeof mainHistoryIndexRoute
  '/notifications/': typeof mainNotificationsIndexRoute
  '/vouchers/$voucherId/redeem': typeof mainVouchersVoucherIdRedeemRoute
  '/vouchers/$voucherId/': typeof mainVouchersVoucherIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof mainIndexRoute
  '/history/$redemptionId': typeof mainHistoryRedemptionIdRoute
  '/notifications/$notificationId': typeof mainNotificationsNotificationIdRoute
  '/history': typeof mainHistoryIndexRoute
  '/notifications': typeof mainNotificationsIndexRoute
  '/vouchers/$voucherId/redeem': typeof mainVouchersVoucherIdRedeemRoute
  '/vouchers/$voucherId': typeof mainVouchersVoucherIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/': typeof mainIndexRoute
  '/(main)/history/$redemptionId': typeof mainHistoryRedemptionIdRoute
  '/(main)/notifications/$notificationId': typeof mainNotificationsNotificationIdRoute
  '/(main)/history/': typeof mainHistoryIndexRoute
  '/(main)/notifications/': typeof mainNotificationsIndexRoute
  '/(main)/vouchers/$voucherId/redeem': typeof mainVouchersVoucherIdRedeemRoute
  '/(main)/vouchers/$voucherId/': typeof mainVouchersVoucherIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history/$redemptionId'
    | '/notifications/$notificationId'
    | '/history/'
    | '/notifications/'
    | '/vouchers/$voucherId/redeem'
    | '/vouchers/$voucherId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history/$redemptionId'
    | '/notifications/$notificationId'
    | '/history'
    | '/notifications'
    | '/vouchers/$voucherId/redeem'
    | '/vouchers/$voucherId'
  id:
    | '__root__'
    | '/(main)'
    | '/(main)/'
    | '/(main)/history/$redemptionId'
    | '/(main)/notifications/$notificationId'
    | '/(main)/history/'
    | '/(main)/notifications/'
    | '/(main)/vouchers/$voucherId/redeem'
    | '/(main)/vouchers/$voucherId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/notifications/': {
      id: '/(main)/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof mainNotificationsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/history/': {
      id: '/(main)/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof mainHistoryIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/notifications/$notificationId': {
      id: '/(main)/notifications/$notificationId'
      path: '/notifications/$notificationId'
      fullPath: '/notifications/$notificationId'
      preLoaderRoute: typeof mainNotificationsNotificationIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/history/$redemptionId': {
      id: '/(main)/history/$redemptionId'
      path: '/history/$redemptionId'
      fullPath: '/history/$redemptionId'
      preLoaderRoute: typeof mainHistoryRedemptionIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/vouchers/$voucherId/': {
      id: '/(main)/vouchers/$voucherId/'
      path: '/vouchers/$voucherId'
      fullPath: '/vouchers/$voucherId/'
      preLoaderRoute: typeof mainVouchersVoucherIdIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/vouchers/$voucherId/redeem': {
      id: '/(main)/vouchers/$voucherId/redeem'
      path: '/vouchers/$voucherId/redeem'
      fullPath: '/vouchers/$voucherId/redeem'
      preLoaderRoute: typeof mainVouchersVoucherIdRedeemRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface mainRouteRouteChildren {
  mainIndexRoute: typeof mainIndexRoute
  mainHistoryRedemptionIdRoute: typeof mainHistoryRedemptionIdRoute
  mainNotificationsNotificationIdRoute: typeof mainNotificationsNotificationIdRoute
  mainHistoryIndexRoute: typeof mainHistoryIndexRoute
  mainNotificationsIndexRoute: typeof mainNotificationsIndexRoute
  mainVouchersVoucherIdRedeemRoute: typeof mainVouchersVoucherIdRedeemRoute
  mainVouchersVoucherIdIndexRoute: typeof mainVouchersVoucherIdIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainIndexRoute: mainIndexRoute,
  mainHistoryRedemptionIdRoute: mainHistoryRedemptionIdRoute,
  mainNotificationsNotificationIdRoute: mainNotificationsNotificationIdRoute,
  mainHistoryIndexRoute: mainHistoryIndexRoute,
  mainNotificationsIndexRoute: mainNotificationsIndexRoute,
  mainVouchersVoucherIdRedeemRoute: mainVouchersVoucherIdRedeemRoute,
  mainVouchersVoucherIdIndexRoute: mainVouchersVoucherIdIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
