/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as mainContactRouteImport } from './routes/(main)/contact'
import { Route as authVerificationRouteImport } from './routes/(auth)/verification'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as mainSettingsIndexRouteImport } from './routes/(main)/settings/index'
import { Route as mainNotificationsIndexRouteImport } from './routes/(main)/notifications/index'
import { Route as mainHistoryIndexRouteImport } from './routes/(main)/history/index'
import { Route as mainNotificationsNotificationIdRouteImport } from './routes/(main)/notifications/$notificationId'
import { Route as mainHistoryRedemptionIdRouteImport } from './routes/(main)/history/$redemptionId'
import { Route as mainVouchersVoucherIdIndexRouteImport } from './routes/(main)/vouchers/$voucherId/index'
import { Route as mainVouchersVoucherIdShareRouteImport } from './routes/(main)/vouchers/$voucherId/share'
import { Route as mainVouchersVoucherIdRedeemRouteImport } from './routes/(main)/vouchers/$voucherId/redeem'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainContactRoute = mainContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => mainRouteRoute,
} as any)
const authVerificationRoute = authVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const mainSettingsIndexRoute = mainSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainNotificationsIndexRoute = mainNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainHistoryIndexRoute = mainHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainNotificationsNotificationIdRoute =
  mainNotificationsNotificationIdRouteImport.update({
    id: '/notifications/$notificationId',
    path: '/notifications/$notificationId',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainHistoryRedemptionIdRoute = mainHistoryRedemptionIdRouteImport.update({
  id: '/history/$redemptionId',
  path: '/history/$redemptionId',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainVouchersVoucherIdIndexRoute =
  mainVouchersVoucherIdIndexRouteImport.update({
    id: '/vouchers/$voucherId/',
    path: '/vouchers/$voucherId/',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainVouchersVoucherIdShareRoute =
  mainVouchersVoucherIdShareRouteImport.update({
    id: '/vouchers/$voucherId/share',
    path: '/vouchers/$voucherId/share',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainVouchersVoucherIdRedeemRoute =
  mainVouchersVoucherIdRedeemRouteImport.update({
    id: '/vouchers/$voucherId/redeem',
    path: '/vouchers/$voucherId/redeem',
    getParentRoute: () => mainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute
  '/verification': typeof authVerificationRoute
  '/contact': typeof mainContactRoute
  '/': typeof mainIndexRoute
  '/history/$redemptionId': typeof mainHistoryRedemptionIdRoute
  '/notifications/$notificationId': typeof mainNotificationsNotificationIdRoute
  '/history/': typeof mainHistoryIndexRoute
  '/notifications/': typeof mainNotificationsIndexRoute
  '/settings/': typeof mainSettingsIndexRoute
  '/vouchers/$voucherId/redeem': typeof mainVouchersVoucherIdRedeemRoute
  '/vouchers/$voucherId/share': typeof mainVouchersVoucherIdShareRoute
  '/vouchers/$voucherId/': typeof mainVouchersVoucherIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/verification': typeof authVerificationRoute
  '/contact': typeof mainContactRoute
  '/': typeof mainIndexRoute
  '/history/$redemptionId': typeof mainHistoryRedemptionIdRoute
  '/notifications/$notificationId': typeof mainNotificationsNotificationIdRoute
  '/history': typeof mainHistoryIndexRoute
  '/notifications': typeof mainNotificationsIndexRoute
  '/settings': typeof mainSettingsIndexRoute
  '/vouchers/$voucherId/redeem': typeof mainVouchersVoucherIdRedeemRoute
  '/vouchers/$voucherId/share': typeof mainVouchersVoucherIdShareRoute
  '/vouchers/$voucherId': typeof mainVouchersVoucherIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(main)': typeof mainRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/verification': typeof authVerificationRoute
  '/(main)/contact': typeof mainContactRoute
  '/(main)/': typeof mainIndexRoute
  '/(main)/history/$redemptionId': typeof mainHistoryRedemptionIdRoute
  '/(main)/notifications/$notificationId': typeof mainNotificationsNotificationIdRoute
  '/(main)/history/': typeof mainHistoryIndexRoute
  '/(main)/notifications/': typeof mainNotificationsIndexRoute
  '/(main)/settings/': typeof mainSettingsIndexRoute
  '/(main)/vouchers/$voucherId/redeem': typeof mainVouchersVoucherIdRedeemRoute
  '/(main)/vouchers/$voucherId/share': typeof mainVouchersVoucherIdShareRoute
  '/(main)/vouchers/$voucherId/': typeof mainVouchersVoucherIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/verification'
    | '/contact'
    | '/'
    | '/history/$redemptionId'
    | '/notifications/$notificationId'
    | '/history/'
    | '/notifications/'
    | '/settings/'
    | '/vouchers/$voucherId/redeem'
    | '/vouchers/$voucherId/share'
    | '/vouchers/$voucherId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/verification'
    | '/contact'
    | '/'
    | '/history/$redemptionId'
    | '/notifications/$notificationId'
    | '/history'
    | '/notifications'
    | '/settings'
    | '/vouchers/$voucherId/redeem'
    | '/vouchers/$voucherId/share'
    | '/vouchers/$voucherId'
  id:
    | '__root__'
    | '/(auth)'
    | '/(main)'
    | '/(auth)/login'
    | '/(auth)/verification'
    | '/(main)/contact'
    | '/(main)/'
    | '/(main)/history/$redemptionId'
    | '/(main)/notifications/$notificationId'
    | '/(main)/history/'
    | '/(main)/notifications/'
    | '/(main)/settings/'
    | '/(main)/vouchers/$voucherId/redeem'
    | '/(main)/vouchers/$voucherId/share'
    | '/(main)/vouchers/$voucherId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  mainRouteRoute: typeof mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/contact': {
      id: '/(main)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof mainContactRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/verification': {
      id: '/(auth)/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof authVerificationRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(main)/settings/': {
      id: '/(main)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof mainSettingsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/notifications/': {
      id: '/(main)/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof mainNotificationsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/history/': {
      id: '/(main)/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof mainHistoryIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/notifications/$notificationId': {
      id: '/(main)/notifications/$notificationId'
      path: '/notifications/$notificationId'
      fullPath: '/notifications/$notificationId'
      preLoaderRoute: typeof mainNotificationsNotificationIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/history/$redemptionId': {
      id: '/(main)/history/$redemptionId'
      path: '/history/$redemptionId'
      fullPath: '/history/$redemptionId'
      preLoaderRoute: typeof mainHistoryRedemptionIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/vouchers/$voucherId/': {
      id: '/(main)/vouchers/$voucherId/'
      path: '/vouchers/$voucherId'
      fullPath: '/vouchers/$voucherId/'
      preLoaderRoute: typeof mainVouchersVoucherIdIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/vouchers/$voucherId/share': {
      id: '/(main)/vouchers/$voucherId/share'
      path: '/vouchers/$voucherId/share'
      fullPath: '/vouchers/$voucherId/share'
      preLoaderRoute: typeof mainVouchersVoucherIdShareRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/vouchers/$voucherId/redeem': {
      id: '/(main)/vouchers/$voucherId/redeem'
      path: '/vouchers/$voucherId/redeem'
      fullPath: '/vouchers/$voucherId/redeem'
      preLoaderRoute: typeof mainVouchersVoucherIdRedeemRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authVerificationRoute: typeof authVerificationRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authVerificationRoute: authVerificationRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface mainRouteRouteChildren {
  mainContactRoute: typeof mainContactRoute
  mainIndexRoute: typeof mainIndexRoute
  mainHistoryRedemptionIdRoute: typeof mainHistoryRedemptionIdRoute
  mainNotificationsNotificationIdRoute: typeof mainNotificationsNotificationIdRoute
  mainHistoryIndexRoute: typeof mainHistoryIndexRoute
  mainNotificationsIndexRoute: typeof mainNotificationsIndexRoute
  mainSettingsIndexRoute: typeof mainSettingsIndexRoute
  mainVouchersVoucherIdRedeemRoute: typeof mainVouchersVoucherIdRedeemRoute
  mainVouchersVoucherIdShareRoute: typeof mainVouchersVoucherIdShareRoute
  mainVouchersVoucherIdIndexRoute: typeof mainVouchersVoucherIdIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainContactRoute: mainContactRoute,
  mainIndexRoute: mainIndexRoute,
  mainHistoryRedemptionIdRoute: mainHistoryRedemptionIdRoute,
  mainNotificationsNotificationIdRoute: mainNotificationsNotificationIdRoute,
  mainHistoryIndexRoute: mainHistoryIndexRoute,
  mainNotificationsIndexRoute: mainNotificationsIndexRoute,
  mainSettingsIndexRoute: mainSettingsIndexRoute,
  mainVouchersVoucherIdRedeemRoute: mainVouchersVoucherIdRedeemRoute,
  mainVouchersVoucherIdShareRoute: mainVouchersVoucherIdShareRoute,
  mainVouchersVoucherIdIndexRoute: mainVouchersVoucherIdIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  mainRouteRoute: mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
